app = "quickshare"
primary_region = "nrt"

[build]

[env]
  NODE_ENV = "production"
  PORT = "8888"
  DB_PATH = "/data/database.sqlite"
  AUTH_ENABLED = "true"

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[[mounts]]
  source = "quickshare_data"
  destination = "/data"
